language: python
python:
  - "2.7"
install:
  - python setup.py develop
script:
  - coverage run `which nosetests` hgapp tests
after_success:
  - coveralls
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
